### ISSUE TITLE
Code Snippets Include a Return at the End

### ISSUE THREAD

**Issue by rdwj** [openshift-cs/rosaworkshop#31]
The code snippets have a return at the end, which makes them auto execute when you paste them into the terminal.

It would be good to end the text at the end of the line for those items where the student needs to go in and edit the command prior to entering.

**Comment by 0kashi** [comment]
Thanks for your feedback.  This is indeed a frustrating bug. This is not due to our workshop files specifically, but rather this seems to affect FireFox only and there has been an [issue opened](https://github.com/squidfunk/mkdocs-material/issues/2021) to address this.  The source  seems to be in this [issue](https://github.com/zenorocha/clipboard.js/issues/707). This doesn't seem to have been addressed yet.
